# Generated by Django 3.2.5 on 2021-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prefix', models.CharField(default=None, max_length=20)),
                ('fromFrameNumber', models.IntegerField()),
                ('toFrameNumber', models.IntegerField()),
            ],
        ),
    ]
