# Generated by Django 3.2.5 on 2021-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('ClassName', models.CharField(default=None, max_length=20)),
                ('CreditScore', models.IntegerField()),
                ('CreditCondition', models.IntegerField()),
                ('CompulsoryFlag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=30)),
                ('username', models.CharField(default='名称未設定', max_length=20)),
                ('credits_list', models.CharField(default='0,0,0,0,0,0,0,0,0,0', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='DownloadLog',
        ),
    ]
